In [11]:
import pandas as pd
import numpy as np

from google.colab import drive 
drive.mount('/content/gdrive')
df = pd.read_csv("/content/gdrive/MyDrive/MachineLearning/MilkGrading.csv")
df.head()

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


pH  Temprature  Taste  Odor  Fat   Turbidity  Colour  Grade
0  6.6          35      1     0     1          0     254    1.0
1  6.6          36      0     1     0          1     253    1.0
2  8.5          70      1     1     1          1     246    0.0
3  9.5          34      1     1     0          1     255    0.0
4  6.6          37      0     0     0          0     255    0.5

In [30]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()

X = df[['pH', 'Temprature', 'Colour']]
X = df[['pH', 'Temprature', 'Colour']] = scale.fit_transform(X = df[['pH', 'Temprature', 'Colour']])
y= df[['Taste', 'Odor', 'Fat ', 'Turbidity', 'Grade']]

print(X)

[[-0.02153136 -0.91410734  0.5016002 ]
 [-0.02153136 -0.81503461  0.26933321]
 [ 1.33656414  2.55343832 -1.35653574]
 ...
 [-2.59476494 -0.41874368  0.73386719]
 [ 0.12142606 -0.12152548 -0.42746777]
 [ 1.40804285  1.06734732  0.73386719]]


In [37]:
df1 = pd.DataFrame(X)
df1.columns=['pH', 'Temprature', 'Colour']

df2 = pd.DataFrame(y)
df2.columns=['Taste', 'Odor', 'Fat ', 'Turbidity', 'Grade']

df3 = pd.concat([df1, df2], axis=1, join='inner')
print(df3)

            pH  Temprature    Colour  Taste  Odor  Fat   Turbidity  Grade
0    -0.021531   -0.914107  0.501600      1     0     1          0    1.0
1    -0.021531   -0.815035  0.269333      0     1     0          1    1.0
2     1.336564    2.553438 -1.356536      1     1     1          1    0.0
3     2.051351   -1.013180  0.733867      1     1     0          1    0.0
4    -0.021531   -0.715962  0.733867      0     0     0          0    0.5
...        ...         ...       ...    ...   ...   ...        ...    ...
1054  0.049947    0.076620 -1.124269      1     1     0          0    0.5
1055  0.049947   -0.616889  0.733867      1     0     1          0    1.0
1056 -2.594765   -0.418744  0.733867      1     1     1          1    0.0
1057  0.121426   -0.121525 -0.427468      1     0     1          0    1.0
1058  1.408043    1.067347  0.733867      0     1     1          1    0.0

[1059 rows x 8 columns]


In [48]:
print(df3.isnull().any())

df3.to_csv(("/content/gdrive/MyDrive/MachineLearning/MilkGradingClean.csv"))
print("Dataframe uploaded to GoogleDrive...")

pH            False
Temprature    False
Colour        False
Taste         False
Odor          False
Fat           False
Turbidity     False
Grade         False
dtype: bool
Dataframe uploaded to GoogleDrive...
